import random

Textos_vox =	[
				'Flaco no me gusta que te hagas el cancherito en un foro on-line. no la agites que soy de pocas pulgas, te estas metiendo con un pesadito, hace 2 meses me fugué del penal de ezeiza con mi compa de celda, hugito "el martillero" le decian, todavía me está buscando la brigada.\nestuve preso por homicidio, narcotráfico, crimen organizado, abuso sexual y tenencia de armas, ya me cantaron en que barrio vivis, cuando quieras voy a golpearte la puerta, a mi no me rompas los huevos porque saco el fusil de abajo del colchón y voy a tu casa a gatillarte la jeta, cuidate negro.',
				'Que difícil que es discutir con pibes hinchas de equipos descendidos, yo gracias a dios que tuve la oportunidad de hinchar por el mas grande y no tener que gritar por equipitos chicos, ser descendido esta bien y es placentero indudablemente pero no se le compara a la gloria y grandeza de ser hincha de boca.\nyo les aconsejaría que dejen hinchar tanto por descendidos y salgan a hinchar por boca, si quieren tener una vida futbolistica activa, no pueden estar toda su vida viviendo de el descenso, eso no es vida loco, tienen que aprovechar la juventud e hinchar por el mas grande todos los días así van a empezar a disfrutar la vida.\nser hincha de boca es mucho mejor que ser descendido, para mi el tema no tiene discusión.',
				'Trabajo en una panadería y siempre viene el gordo pelotudo del OP, hoy yo estaba atendiendo y escuchó que el gordo este pega un portazo y entra a los gritos, "por favor calmate un poco, ya te atiendo" le dije, pero el gordo estaba sacado y seguía gritando, le pedí disculpas a la otra clienta que se veia asustada y le dije que lo iba a atender a él primero para que se calme un poco.\nel gordo se acercó a los gritos hasta el mostrador, tenía alta baranda, "calmate y decime qué querés" el gordo me dijo, "dafaturas las faturas" le pregunte cuales, "las faturas tenian poco dulceleche capo" y ahí me acordé que ayer a la tarde el pelotudo vino a comprar dos docenas y media de facturas y una cindor, entonces digo "si ya te las comiste no puedo hacer nada" y me dice "me tenes que dar otras mostro" en eso vino mi jefe, el op se había agarrado un churro y se lo estaba comiendo.\n"dale dale capo, tengo que volver a vosed" dijo el gordo, entonces mi jefe viendo que no había otra manera para que se vaya le trajo tarro de dulce de leche vencido,el gordo lo agarró y amagó a irse, pero mi jefe le dijo "te tengo que cobrar el churro que te comiste pibe", el op volvió, tiró un billete de $20 sobre el mostrador, se tropezó y se fue corriendo',
				'Trabajo en una panadería y siempre viene el gordo pelotudo del op, el otro día vino en una bici con canastito toda despintada, la dejó sobre la vereda, obstruyendola, y entró de una forma muy agresiva al negocio, le pedí que tenga más cuidado con la puerta, se acerca y me pide gritando una docena de medialunas y media docena de tortitas negras, le digo que espere que estaba atendiendo a otra clienta.\nsale del local, agarra la bicicleta y la acomoda, luego empieza a dar vuelta como autista por 2 minutos, ahi vuelve a entrar, me dice que me apure que dejó descargando porno de trapitos y que tiene miedo de que su vieja se entere, le preparo el pedido para que deje de molestar, agarra todo, suelta un "yaguareté" sobre el mostrador y sale apurado, agarra la bicicleta y al intentar pedalear se le sale la cadena, acto seguido cae al piso y se desparraman todas las facturas, se levanta, agarra un puñado de facturas con cada mano y sale corriendo mientras se mete una medialuna en la boca.',
				'QUERES BAJAR Y NOS FAJAMOS BOLUDO? QUERES BAJAR Y NOS FAJAMOS? POR QUE YA ME HARTASTE TARADO, YA ME HARTASTE ESTÚPIDO, QUERES BAJAR Y NOS FAJAMOS? ENTONCES TERMINALA, TERMINALA DE BARDEARME, ME ESTAS BARDEANDO DESDE HOY LOCO!',
				'sabes lo que pasa anon? yo me pasó el tiempo necesario para crear un vox de calidad, elijo una imagen acordé a la temática del vox y hago una redacción al nivel de esta página, para intentar crear un debate donde predomine un intercambio de ideas enriquecedor.\nahora,todo eso ocurre en mi mente, pero la realidad es que viene un ANON generalmente amarillo o verde y empieza a insultar al OP infantilmente, tratando de desvirtuar el vox, despreciando totalmente el contenido del mismo y a su creador con el único afan de vanagloriarse entre sus pares.\ny eso me molesta, realmente me molesta mucho porque mi planificación se ve saboteada por un sujeto que no tiene el más mínimo respeto por los vox ajenos, yo quisiera averiguar quién sos y que tengamos una charla face too face, me entendes? quizás teniéndote a pocos centímetros de mi ser pueda comprender en un rápido análisis visual tus trastornos cognitivos que te llevan a cometer estos actos y con una certera piña al mentón pueda corregirlos.\npero bueno eso como te decía ocurre en mi mente así que seguiré intentando repelerte poniendo en el titulo (vox serio) saludos.',
				'antes de que me des una a mí, antes que me toques un cachito tenés 50 trompadas en la jeta forro de mierda, july3p forro de mierda, 50 en la jeta, y una cosa, por ahí te vas con un balazo en la cabeza forro de mierda, ¿a quien carajo te crees que vas a joder y a prepotear? a tu abuelita forro de mierda, a tu abuelita.\nte vas con un balazo en la cabeza de acá, te vas con un balazo en la cabeza, llorando te vas a ir de acá pelotudito de mierda, qué burlando ni qué mierda ni que tu hijo ni que la concha de tu puta madre, que la reputa madre que te recontra puta parió.',
				'BASTA FLACO ME TENES CANSADO SIEMPRE TIRANDO MALA ONDA EN TODOS LOS VOXS QUE CREO VOS SOS EL MISMO PORQUE SIEMPRE ESCRIBEN DE LA MISMA MANERA CANSADO ME TENES YO VENGO ACA HUMILDEMENTE A CREAR VOXS PARA SACAR UNA SONRISA Y DEBES EN CUANTO UNA PREGUNTA EN LO QUE TENGO UNA DUDA Y VOS VENIS CORRIENDO, A FALTARME EL RESPETO SIN NINGUNA RAZON PORQUE YO A VOS NO TE CONOZCO YO A VOS NO TE HICE NADA SIN EMBARGO EN TODOS LOS VOXS ME ESTAS ACOSANDO PARECE QUE SOS MOD PORQUE SABES QUIEN SOY SIEMPRE ME PERSEGUIS ESTO DEBE SER REVISADO POR CODUBI PORQUE ESTO ES ACOSO NENE ESTO ES ACOSO, LA DUDA YA ME LA RESOLVIERON LOS DEMAS CIERRO EL VOX Y ESPERO NO VOLVERTE A ENCONTRARTE NUNCA MAS EN MI VIDA',
				'HOLA AMIGOS DE IUTUB, VOY HACER OTRA TROLLEADA POR TELEFONO JJJJA VOY A LLAMAR A CUALQUIER NUMERO Y VOY A PREGUNTAR POR EL DOCTOR PERALTA EL QUE SE TIRA UN PEDO Y SALTA CUALQUIERA\nHABLE.\nSE ENCUETRA EL DOCTOR PERALTA ?\n-QUE DOCTOR PERALTA?\nEL QUE SE TIRA UN PEDO Y SALTA\n-ANDATE A LA CONCHA DE TU MADRE PENDEJO DE MIERDA\n...\nHIHIHIJO DE PUTAA HIHIJA DE PUTA COMO... JAJAJAJAJAA JJAAJAAJAJ JAJA JA JEJE... ENCIMA SUSCRIBANSE A MI CANAL PARA MAS DE ESTO PORQUE ESTA MO... MUICK MUICK TA BUENISIMO SE CAGAMO TODO DE RISO\nUTA JAJAJJJJA JKKK ESTA GRABADO QUIJA DE PUTA JKKJAJ HAAJJ QUIJA DE PUTA JAAJEJEJJAJK ES LO MAS GRACIOSO DEL MUNDO CHICOOS... SI NO SE ESTAN CAGANDO DE RISA CON ESTO SEGURO QUE... QUE VOY Y ME TIRO UN ANCLA EN EL MAR HAHAJKKKK JAJAJAJ JA JAJAJAJA POR FAVOR SI TE ESTAS CAGANDO DE RISA DE VUELVA SUSCRIBITE A MI CANAL PONELE ME GUSTA Y VA A VENIR UN PAR DE VIDEO MAS MAA.. MAÑANA DESPUES MAS ASI POE TAN BUENISIMO LA GENTE SE ENOJA ES ASI LA GENTE JAJKKJA MEDA HASTA LA PROTSIMAAAAAAAA'
]

Textos_ban = [
				'Vete a hacer el graciosillo a otro lado, listillo.',
				'¿Querías atención? Tomá, atención personalizada.',
				'No me hagas perder el tiempo, por favor.',
				'Suficiente circo por hoy, payasito. Descansá un rato.',
				'Vete a hacer el graciosillo a otro servidor, tontuelo.'
]


def frase_voxera():
	rand = random.randint(0, len(Textos_vox) - 1)
	return Textos_vox[rand]

def frase_ban():
	rand = random.randint(0, len(Textos_ban) - 1)
	return Textos_ban[rand]